### ISSUE TITLE
Expected resource locations for UoM API?

### ISSUE THREAD

**Issue by timbrisc** [ucum-org/ucum#49]
*Issue migrated from trac ticket # 42*

**priority:** major | **resolution:** fixed | **keywords:** formatting

#### 2010-06-07 14:36:31: jonathanb@mirthcorp.com created the issue

___
> I'm attempting to use the UoM API and I am having some difficulty with the initialization. 
> 
> I'm attempting to use a very simple case:
> ```
> Unit unit = UnitFormat.getInstance().parse("some unit string");
> ```
> 
> 
> I am getting an error
> ```
> java.lang.Error: No service provider found for org.unitsofmeasure.util.UnitFormatProvider
>         at org.unitsofmeasure.util.UnitFormat.findJarServiceProvider(UnitFormat.java:173)
>         at org.unitsofmeasure.util.UnitFormat.<clinit>(UnitFormat.java:51)
> ```
> 
> I looked at UnitFormat.java and it appears to be using a resource loader looking in META-INF/services. I placed the UoM JAR in that path in my project and still no luck.
> 
> Where should the UoM JARs be located within a project so that the resources can be found??

**Comment by timbrisc** [comment]
#### 2010-07-29 19:05:47: werner.keil@gmx.net changed status from *new* to *closed*

**Comment by timbrisc** [comment]
#### 2010-07-29 19:05:47: werner.keil@gmx.net set resolution to *fixed*

**Comment by timbrisc** [comment]
#### 2010-07-29 19:05:47: werner.keil@gmx.net commented


___
> Sorry if this may have caused confustion. After thorough checks against target containers especially OSGi this mechanism from Java 6 was found to be incompatible. Mainly due to circular dependencies between an implementing OSGi bundle and the base API.
> 
> The latest version of UOM API no longer contains a concrete or abstract class named UnitFormat, but an interface. Driving reason beside the mentioned issue were further inspiration by the JSR-108 successor UCAR (where this exists in a similar way) and different class hierarchies e.g. under Eclipse and ICU4J as opposed to other frameworks. A direct dependency to java.util.text.Format wasn't suitable for some of these ecosystems as others (ICU4J) define their own subclasses of that class while others use entirely different formatters.
> 
> Test code shows 2 examples named BaseFormat and SimpleFormat using the new interface. Those are blueprints, so in non-test code, please implement your own. Contributions to the test code are welcome while further unit tests are gradually added.
> 
> Replying to [#42 jbartels]:
> > I'm attempting to use the UoM API and I am having some difficulty with the initialization. 
> > 
> > I'm attempting to use a very simple case:
> > ```
> > Unit unit = UnitFormat.getInstance().parse("some unit string");
> > ```
> > 
> > 
> > I am getting an error
> > ```
> > java.lang.Error: No service provider found for org.unitsofmeasure.util.UnitFormatProvider
> >         at org.unitsofmeasure.util.UnitFormat.findJarServiceProvider(UnitFormat.java:173)
> >         at org.unitsofmeasure.util.UnitFormat.<clinit>(UnitFormat.java:51)
> > ```
> > 
> > I looked at UnitFormat.java and it appears to be using a resource loader looking in META-INF/services. I placed the UoM JAR in that path in my project and still no luck.
> > 
> > Where should the UoM JARs be located within a project so that the resources can be found??
>
